version: '3'

services:
  drupal-cms:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    image: custom-drupal
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres-db:
    image: postgres:11.6
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
   drupal-modules:
   drupal-profiles:
   drupal-sites:
   drupal-themes:
   drupal-data:

# run docker-compose up to get this shit spinnnnnin baby!!!